/**
 * Handwritten response bodies shaped from the published API schemas.
 *
 * Nothing here is captured from a live request: a fixture that has to be
 * recorded cannot be regenerated by anyone reading the tests.
 */

export type SummaryOverrides = {
  runTime?: number | null;
  rating?: number | null;
  releaseYear?: number | null;
  directors?: Array<{ name: string }>;
  poster?: { sizes: Array<{ width: number; url: string }> } | null;
  link?: string | null;
};

/** One `FilmSummary`, with every field the watchlist endpoint returns. */
export function filmSummary(id: string, over: SummaryOverrides = {}) {
  const item: Record<string, unknown> = {
    type: "FilmSummary",
    id,
    name: `Film ${id}`,
    fullDisplayName: `Film ${id}`,
    sortingName: `Film ${id}`,
    adult: false,
    reviewsHidden: false,
    releaseYear: over.releaseYear === undefined ? 1994 : over.releaseYear,
    directors: over.directors ?? [{ name: "A Director" }],
  };
  if (over.runTime !== null) item.runTime = over.runTime ?? 100;
  if (over.rating !== null) item.rating = over.rating ?? 3.9;
  if (over.link !== null) item.link = over.link ?? `https://letterboxd.com/film/${id}/`;
  if (over.poster !== null) {
    item.poster = over.poster ?? {
      sizes: [
        { width: 125, url: `https://a.ltrbxd.com/${id}-125.jpg` },
        { width: 300, url: `https://a.ltrbxd.com/${id}-300.jpg` },
        { width: 600, url: `https://a.ltrbxd.com/${id}-600.jpg` },
      ],
    };
  }
  return item;
}

/** A `FilmsResponse`. `next` is returned in the `cursor=` form the API uses. */
export function filmsResponse(ids: string[], next?: string, over: SummaryOverrides = {}) {
  return {
    items: ids.map((id) => filmSummary(id, over)),
    ...(next ? { next: `cursor=${encodeURIComponent(next)}` } : {}),
  };
}

/** A `SearchResponse` carrying `MemberSearchItem`s, in the order given. */
export function memberSearch(members: Array<{ id: string; username: string }>) {
  return {
    items: members.map((m, i) => ({
      type: "MemberSearchItem",
      score: 10 - i,
      member: {
        id: m.id,
        username: m.username,
        displayName: m.username,
        shortName: m.username,
        memberStatus: "Member",
        accountStatus: "Active",
      },
    })),
  };
}

/** A `MemberStatistics` body, of which only `counts.watchlist` is read. */
export function statistics(watchlist: number) {
  return { counts: { watchlist, watched: 0, films: 0, listCount: 0 } };
}

/** An `AccessToken` body from the client-credentials grant. */
export function accessToken(value = "test-token", expiresIn = 3600) {
  return { access_token: value, token_type: "bearer", expires_in: expiresIn };
}

export function json(body: unknown, status = 200, headers: Record<string, string> = {}): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", ...headers },
  });
}
